# Kubernetes
kube_version: v1.9.6
token: b0f7b8.8d1767876297d85c

# Should etcd certificates be generated if not found in local or in first etcd node
etcd_generate_certs: true

# Etcd version to install
etcd_version: v3.3.2

# Should kubernetes certificates be generated if not found in local or in first controller
kubernetes_generate_certs: true

# An NGiNX load balancer will be spinned up on each node to be able to load
# balance the calls to the API servers (only if there are more than one
# controller)
use_nginx_loadbalancer: true

# This variables can set which NGiNX image/version to use
nginx_image_repo: nginx
nginx_image_tag: 1.13

init_opts: ""
controller_domains: []
kubeadm_opts: ''

service_subnet: 10.96.0
service_cidr: "{{ service_subnet }}.0/12"
dns_name: cluster.local
dns_ip: "{{ service_subnet }}.10"

# Network implementation('flannel', 'calico')
network: flannel
pod_network_cidr: 10.244.0.0/16
cni_opts: "interface=eth1" # flannel: --iface=eth1, calico: interface=eth1

# A list of insecure registrys you might need to define
insecure_registrys: ""
# insecure_registrys=['gcr.io']

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
