---

- name: Install etcd
  unarchive:
    src: https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: [--strip-components=1]
    remote_src: yes
