---

- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: "Create pki directory in all controllers"
  file:
    path: /etc/kubernetes/pki
    state: directory

- name: "Copy generated certificates to all controllers"
  copy:
    src: "secrets/pki/{{ item.file }}"
    dest: "/etc/kubernetes/pki/{{ item.file }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  with_items:
  - file: ca.crt
    mode: "0644"
  - file: ca.key
    mode: "0600"
  - file: front-proxy-ca.crt
    mode: "0644"
  - file: front-proxy-ca.key
    mode: "0600"
  - file: sa.pub
    mode: "0600"
  - file: sa.key
    mode: "0600"

- name: Init Kubernetes cluster
  when: reset_cluster|succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --apiserver-advertise-address {{ ip }} \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-cert-extra-sans "{{ controller_domains_list }}" \
                 --token {{ token }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet

- name: test kubectl get nodes
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl get nodes
  register: result_get_nodes

- name: test kubectl get nodes result
  shell: test {{ result_get_nodes.rc}} -eq 0
