---

- name: Check if local certificates exist
  command: test -f secrets/kubernetes/pki/"{{ item }}"
  with_items:
   - ca.crt
   - ca.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - sa.pub
   - sa.key
  become: false
  run_once: true
  ignore_errors: true
  delegate_to: localhost
  register: kubernetes_certs_exist

- name: "Trying to fetch certificates from {{ groups['kube-controllers'][0] }}"
  fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: secrets/kubernetes/{{ item }}
    flat: yes
    fail_on_missing: true
  when: kubernetes_certs_exist|failed
  with_items:
   - ca.crt
   - ca.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - sa.pub
   - sa.key
  run_once: true
  ignore_errors: true
  register: kubernetes_certs_fetched

- fail:
    msg: "Certificates not found and kubernetes_generate_certs=false on the configuration!"
  when: kubernetes_certs_fetched|failed and kubernetes_certs_exist|failed and (kubernetes_generate_certs == false or kubernetes_generate_certs is not defined)

- name: "Generate certificates on {{ groups['kube-controllers'][0] }}"
  command: kubeadm alpha phase certs all
  when: kubernetes_certs_fetched|failed and kubernetes_certs_exist|failed
  run_once: true

- name: "Fetch generated certificates from {{ groups['kube-controllers'][0] }}"
  fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: secrets/kubernetes/pki/{{ item }}
    flat: yes
    fail_on_missing: true
  when: kubernetes_certs_fetched|failed and kubernetes_certs_exist|failed
  with_items:
   - ca.crt
   - ca.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - sa.pub
   - sa.key
  run_once: true
