---

- name: "Get node token from controller {{ groups['kube-controllers'][0] }}"
  command: kubeadm token create
  run_once: true
  delegate_to: "{{ groups['kube-controllers'][0] }}"
  register: get_kubeadm_token

- name: "Get CA hash from controller {{ groups['kube-controllers'][0] }}"
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  run_once: true
  delegate_to: "{{ groups['kube-controllers'][0] }}"
  register: get_kubeadm_ca_hash
