---

- name: Join to Kubernetes cluster in {{ hostvars[groups['kube-controllers'][0]]['ip'] }}
  when: get_kubeadm_token.rc == 0 and get_kubeadm_ca_hash.rc == 0
  shell: |
    kubeadm join --token {{ get_kubeadm_token.stdout }} \
                 --discovery-token-ca-cert-hash sha256:{{ get_kubeadm_ca_hash.stdout }} \
                 --node-name {{ inventory_hostname }} \
                 {{ hostvars[groups['kube-controllers'][0]]['ip'] }}:6443
  register: join_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet

- name: Label nodes as nodes
  command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/node=
  environment:
    KUBECONFIG: "/etc/kubernetes/kubelet.conf"

- name: Label nodes with their custom labels
  command: kubectl label node {{ inventory_hostname }} {{ item }}
  environment:
    KUBECONFIG: "/etc/kubernetes/kubelet.conf"
  with_items: "{{ custom_labels }}"
