---
- name: Test if node is already in the cluster checking on the controller
  shell: kubectl get nodes | grep '{{ ansible_hostname }}\s*Ready'
  register: node_is_in_cluster_controller
  delegate_to: "{{ groups['kube-controllers'][0] }}"
  ignore_errors: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: Test if node is already in the cluster checking on the node
  shell: kubectl get nodes | grep '{{ ansible_hostname }}'
  register: node_is_in_cluster_node
  when: node_is_in_cluster_controller.rc == 0
  delegate_to: "{{ groups['kube-controllers'][0] }}"
  ignore_errors: true
  environment:
    KUBECONFIG: "/etc/kubernetes/kubelet.conf"

- name: Set if node is already in the cluster
  set_fact:
    node_is_in_cluster: "{{ node_is_in_cluster_controller.rc == 0 and node_is_in_cluster_node.rc == 0 }}"

- name: Reset Kubernetes component
  when: get_kubeadm_token.rc == 0 and get_kubeadm_ca_hash.rc == 0 and node_is_in_cluster == false
  shell: "kubeadm reset"
  register: reset_cluster

- name: Join to Kubernetes cluster in {{ groups['kube-controllers'][0] }}
  when: get_kubeadm_token.rc == 0 and get_kubeadm_ca_hash.rc == 0 and node_is_in_cluster == false
  shell: |
    kubeadm join --token {{ get_kubeadm_token.stdout }} \
                 --discovery-token-ca-cert-hash sha256:{{ get_kubeadm_ca_hash.stdout }} \
                 {{ hostvars[groups['kube-controllers'][0]]['ip'] }}:6443
  register: join_cluster

- name: Enable and restart kubelet engine
  when: node_is_in_cluster == false
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
