---

- include_tasks: get_kubeadm_credentials.yml

- include_tasks: join_cluster.yml

- name: Test kubectl get nodes returns all nodes
  shell: kubectl get nodes | grep '{{ ansible_hostname }}'
  register: result_get_nodes
  until: result_get_nodes.rc == 0
  environment:
    KUBECONFIG: "/etc/kubernetes/kubelet.conf"
  retries: 5

- include_tasks: node_labels.yml

- include_tasks: nginx_apiserver.yml
  when: use_nginx_loadbalancer == true and groups['kube-controllers']|length > 1
