---

- name: Add kubernetes entries to hosts files
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ec2_private_ip_address }}[ \t]+{{ item }}'
    line: "{{ hostvars[item].ec2_private_ip_address }}\t{{ hostvars[item].ansible_ssh_host }} {{ item }}"
    insertafter: EOF
    state: present
  with_items: "{{ groups['kube-all'] }}"

- name: Set net.ipv4.ip_forward on all nodes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Set net.bridge.bridge-nf-call-iptables on all nodes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- include_tasks: logrotate.yml
