---

- name: "Check if cluster already exists and is health"
  shell: "etcdctl cluster-health | grep -q 'cluster is healthy'"
  register: etcd_cluster_is_healthy
  ignore_errors: true
  changed_when: false
  check_mode: no
  environment:
    ETCDCTL_ENDPOINTS: "{{ etcd_access_urls }}"
    ETCDCTL_CERT_FILE: "/etc/etcd/pki/client.pem"
    ETCDCTL_KEY_FILE: "/etc/etcd/pki/client-key.pem"
