---

- name: Create Kubernetes config directory
  file: path=/{{ ansible_user_id }}/.kube/ state=directory

- name: Copy config file to HOME/.kube dir
  command: "{{ item }}"
  with_items:
    - mkdir -p ~{{ ansible_user }}/.kube
    - cp /etc/kubernetes/admin.conf ~{{ ansible_user }}/.kube/config
    - chown -R {{ ansible_user }}:{{ ansible_user }} ~{{ansible_user }}/.kube
    - chmod 0400 ~{{ ansible_user }}/.kube/config
