---
- name: Check if local certificates exist
  local_action: stat path=secrets/pki/{{ item }}
  with_items:
   - ca.crt
   - ca.key
   - apiserver.crt
   - apiserver.key
   - apiserver-kubelet-client.crt
   - apiserver-kubelet-client.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - front-proxy-client.crt
   - front-proxy-client.key
   - sa.pub
   - sa.key
  become: false
  ignore_errors: true
  register: certs_exist

- fail:
    msg: "Certificates not found and generate_certs=false on the configuration!"
  when: certs_exist is not defined and (generate_certs == false or generate_certs is not defined)

- name: "Generate certificates on a controller"
  command: kubeadm alpha phase certs all \
            --apiserver-cert-extra-sans "{{ controller_domains_list }}"
  when: certs_exist is not defined
  run_once: true

- name: "Fetch generated certificates"
  fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: secrets/pki/{{ item }}
    flat: yes
  with_items:
   - ca.crt
   - ca.key
   - apiserver.crt
   - apiserver.key
   - apiserver-kubelet-client.crt
   - apiserver-kubelet-client.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - front-proxy-client.crt
   - front-proxy-client.key
   - sa.pub
   - sa.key
  run_once: true

- name: "Distribute generated certificates to all controllers"
  copy:
    src: "secrets/pki/{{ item.file }}"
    dest: "/etc/kubernetes/pki/{{ item.file }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  with_items:
  - file: ca.crt
    mode: "0644"
  - file: ca.key
    mode: "0600"
  - file: apiserver.crt
    mode: "0644"
  - file: apiserver.key
    mode: "0600"
  - file: apiserver-kubelet-client.crt
    mode: "0644"
  - file: apiserver-kubelet-client.key
    mode: "0600"
  - file: front-proxy-ca.crt
    mode: "0644"
  - file: front-proxy-ca.key
    mode: "0600"
  - file: front-proxy-client.crt
    mode: "0644"
  - file: front-proxy-client.key
    mode: "0600"
  - file: sa.pub
    mode: "0600"
  - file: sa.key
    mode: "0600"
