---

- name: Create kubeadm-config.json
  template:
    src: kubeadm-config.json.j2
    dest: /etc/kubernetes/kubeadm-config.json
    owner: root
    group: root
    mode: 0644

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --config=/etc/kubernetes/kubeadm-config.json \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet

- name: Test kubectl get nodes returns all controllers
  shell: kubectl get nodes | grep '{{ ansible_hostname }}'
  register: result_get_nodes
  until: result_get_nodes.rc == 0
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  retries: 5
