---

- name: PKI infrastructure configuration
  include_tasks: pki/fetch.yml

- name: Reset Kubernetes component
  shell: "kubeadm reset"
  register: reset_cluster

- name: Distribute PKI's CAs
  include_tasks: pki/distribution.yml

- name: Etcd client certificates
  include_tasks: etcd_certs.yml

- name: Initialise controllers
  include_tasks: kubeadm.yml

- name: Create user configuration
  include_tasks: user_configuration.yml

