---

- name: Set full controller's domain list
  when:
    - controller_domains is not defined or controller_domains == ""
  set_fact:
    controller_domains_list: "kubernetes"

- name: Set full controller's domain list
  when:
    - controller_domains is defined and controller_domains != ""
  set_fact:
    controller_domains_list: "kubernetes,{{ controller_domains }}"

- name: PKI infrastructure configuration
  include_tasks: pki/fetch.yml

- name: Initialise controllers
  include_tasks: kubeadm/main.yml

- name: Create user configuration
  include_tasks: config/main.yml

