---

- name: Create Kubernetes config directory
  file:
    path: ~{{ ansible_user }}/.kube/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy config file to HOME/.kube dir
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0400"

- name: Download kubeconfig file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ local_kubernetes_secrets_dir }}/kubeconfig"
    flat: true
  run_once: true
