---
- name: Backup etcd data
  command: /bin/true
  notify:
    - Refresh Time Fact
    - Set Backup Directory
    - Create Backup Directory
    - Stat etcd v2 data directory
    - Backup etcd v2 data
    # - Backup etcd v3 data
  when: etcd_cluster_is_healthy.rc == 0

- name: Refresh Time Fact
  setup: filter=ansible_date_time

- name: Set Backup Directory
  set_fact:
    etcd_backup_directory: "/var/lib/etcd/backup/etcd-{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

- name: Create Backup Directory
  file:
    path: "{{ etcd_backup_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Stat etcd v2 data directory
  stat:
    path: "/var/lib/etcd/member"
  register: etcd_data_dir_member

- name: Backup etcd v2 data
  when: etcd_data_dir_member.stat.exists
  command:  etcdctl backup --data-dir /var/lib/etcd --backup-dir {{ etcd_backup_directory }}
  environment:
    ETCDCTL_API: 2
  retries: 3
  delay: 3

# - name: Backup etcd v3 data
#   command: etcdctlsnapshot save {{ etcd_backup_directory }}/snapshot.db
#   environment:
#     ETCDCTL_API: 3
#     ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"
#     ETCDCTL_CA_FILE: "/etc/etcd/pki/ca.pem"
#     ETCDCTL_CERT_FILE: "/etc/etcd/pki/client.pem"
#     ETCDCTL_KEY_FILE: "/etc/etcd/pki/client-key.pem"
#   retries: 3
#   delay: 3
